_core:
  default_config_hash: wB2h-QBawANCiCVEXy6bJjiDfvZY6EONZ6-wRB_RYQc
langcode: es
hotlink: false
origin: 'http://dev-site-andrespereira.pantheonsite.io'
origin_dir: sites/default/files
use_imagecache_root: true
verify: true
